version: '3'

services:
  h1:
    hostname: h1
    build: host
    networks:
      - net
    cap_add:
      - NET_ADMIN
    volumes:
      - ${ARG_control}/h1:/control
  h2:
    hostname: h2
    build: host
    networks:
      - net
    cap_add:
      - NET_ADMIN
    volumes:
      - ${ARG_control}/h2:/control


networks:
  net:
