version: '3'

services:
  client:
    hostname: client
    image: ${ARG_repository}traffic-simulator:${VERSION}
    networks:
      - net
    cap_add:
      - NET_ADMIN
    volumes:
      - ${ARG_control}/client:/control
  server:
    hostname: server
    image: ${ARG_repository}traffic-simulator:${VERSION}
    networks:
      - net
    cap_add:
      - NET_ADMIN
    volumes:
      - ${ARG_control}/server:/control


networks:
  net:
